services:
  - type: web
    name: ink-echo-blog
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn auth_blog.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: auth_blog.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: ink-echo-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_ALLOWED_HOSTS
        value: blog-project-django-zh3z.onrender.com,localhost,127.0.0.1

databases:
  - name: ink-echo-db
    plan: free
    region: oregon
